### ISSUE TITLE
How to deploy the TokenCacheDb to Azure?

### ISSUE THREAD

**Issue by mostafaasad** [OfficeDev/O365-ASPNETMVC-Start#11]
I have run the project successfully in local machine. Would like to test in Azure. How to deploy the database (.mdf) file to SQL Azure?

**Comment by MIchaelMainer** [comment]
Hello mostafaasad,
I'm glad to hear that you got this running on your local machine.
I've never tried to deploy an mdf to SQL Azure. I might try with this topic: http://azure.microsoft.com/en-us/documentation/articles/sql-database-deploy/
Then I'd image you'd need to update the connection string to point at that Azure db. I might try this topic: https://msdn.microsoft.com/en-us/library/azure/ee336243.aspx
I hope this helps.

**Comment by mostafaasad** [comment]
Hello Michael,
Thanks for the reply. I have been successful deploying the CacheDB in Aziure by creating a database and creating new connection string for the DB. The App worked in the Cloud as expected.

Regards,
Mostafa

**Comment by MIchaelMainer** [comment]
Hello Mostafa,
This is great news! Thank you for letting me know about your success.
With regards,
Michael
