### ISSUE TITLE
Unable to sign-in

### ISSUE THREAD

**Issue by zombieland** [OfficeDev/O365-ASPNETMVC-Start#12]
Hey guys,
When I run the project, the home page comes up but It doesn't go pass the signin page. When I click on sign in, It redirects to "https://login.windows.net", then it redirects to a blank page with http://localhost URL.

I've entered necessary credentials on web.config and register it on service manager.
```<add key="webpages:Version" value="3.0.0.0" />
    <add key="webpages:Enabled" value="false" />
    <add key="ClientValidationEnabled" value="true" />
    <add key="UnobtrusiveJavaScriptEnabled" value="true" />
    <add key="ida:GraphResourceId" value="https://graph.windows.net" />
    <add key="ida:GraphUserUrl" value="https://graph.windows.net/{0}/me?api-version=2013-11-08" />
    <add key="ida:TenantID" value="6f321bc2-998******************"/>
    <add key="ida:ClientID" value="71bd5ba8-2c38*****************" />
    <add key="ida:Password" value="LWCyzPloey5JJgTgAI*******/>
    <add key="ida:AuthorizationUri" value="https://login.windows.net" /></appSettings>```

![service_manager_screenshot](https://cloud.githubusercontent.com/assets/11508035/6793081/e35f502e-d17c-11e4-8c20-f7da131e032e.PNG)

**Comment by AndrewJByrne** [comment]
Hey Zombieland, 

To use the project as-is, you need to set the permissions as per step 6 in the Register app to consume Office 365 APIs part of the Readme. In particular, getting a blank redirect implies the Users and Groups permission isn't set. 

Let us know if that helps, 

Andrew

**Comment by zombieland** [comment]
Hi Andrew,
It looks like I do have proper delegated permissions. Now, I've added application permissions but still no luck. Please see below screenshot. 

I don't think it's an issue with my instance since calendar entries come back using the API Sandbox (which is awesome BTW). Please help.

![permissioncapture](https://cloud.githubusercontent.com/assets/11508035/6793591/e0d3817a-d183-11e4-808d-8eb0a9c6861b.PNG)

**Comment by AndrewJByrne** [comment]
Looking at your screenshot, I am not seeing permissions for Windows Azure Active Directory. The delegated permission in that case would be "Enable sign-on and read users' profiles". This would  have been added during the Add Connected Services step if you had set that permission.

**Comment by zombieland** [comment]
Hi Andrew,
Please see my screenshot below. Am I looking at the wrong screen? 

![permissioncapture](https://cloud.githubusercontent.com/assets/11508035/6794143/6937ec66-d18b-11e4-8ea9-99f9e7f15c5f.PNG)

**Comment by AndrewJByrne** [comment]
Hi Zombieland, 

it is the right screen, but your permissions don't look right. It looks like you have super-user permissions for exchange :-) 
You should be able to click on the big green button "Add application", then add Windows Azure Active Directory from the dialog that pops up. Once that succeeds, you should see a new line in your permissions to other applications list. It will look like this:

![aad_perm](https://cloud.githubusercontent.com/assets/8550529/6794401/802b96f4-d18e-11e4-9bc6-af64106afb71.PNG)

The actual permission you then need to select is this one:
![perm_select](https://cloud.githubusercontent.com/assets/8550529/6794412/a667f222-d18e-11e4-9163-cca27677b137.PNG)

The right permissions should have been added when you followed the Readme instructions. However, hopefully this will unblock you. 

Andrew

**Comment by zombieland** [comment]
Thanks a lot Andrew!! We are moving away from Google Apps to Office 365 here at Nutanix. You guys rock!

**Comment by AndrewJByrne** [comment]
Woohoo on us rocking and your migration path! :-)  Glad I could help.

**Comment by lnyswonger** [comment]
Awesome.

Sent from my Windows Phone
________________________________
