### ISSUE TITLE
Web.config missing the settings placeholders

### ISSUE THREAD

**Issue by matvelloso** [OfficeDev/O365-ASPNETMVC-Start#16]
I know the intention is to have the developer right-clicking and adding connected services but this might not be what many developers want to do. At least the web.config should already point out to the right setting keys and leave them blank

**Comment by MIchaelMainer** [comment]
@matvelloso 

Thank you for the feedback. That makes sense. I made sure that the Connected Services tool handles that. I've made the change and checked it in.

Thank you.
