### ISSUE TITLE
Blank page after successful sign in

### ISSUE THREAD

**Issue by niravnvs** [OfficeDev/O365-ASPNETMVC-Start#18]
Hi,
I am using this solution as starting point for my MVC application showing Office 365 list data. I was able to apply right configurations (tenantid, clientID etc..). Once I click sign in and enter username password for my Office 365 tenant I get blank page. Could you please let me know what could be missing? Please see my configurations below:
<add key="ida:GraphResourceId" value="https://graph.windows.net" />
  <add key="ida:ClientId" value="9332cf3d-c0a5-44cb-9aa2-4fd2e2a422c3" />
    <add key="ida:TenantID" value="f14f1d4a-f020-45ee-ac6c-758614918c0b" />
    <add key="ida:AADInstance" value="https://login.windows.net/{0}" />
  <add key="ida:ClientSecret" value="uzelE6HwQAUk3iSjd4FC3+dewk4zvLDQBIW+LGTnWvk=" />

**Comment by bmitchell287** [comment]
Hi niravnvs, would you please make sure that all of your service permissions are correctly configured in the "Services Manager" menu (Add connected service)?  Especially that the "Sign you in and read your profile" option is selected. The sample readme will guide you if needed.

◦(Users and Groups) – Sign you in and read your profile (Read)

Thanks.

**Comment by bmitchell287** [comment]
Hi niravnvs, I'm going to close this bug. If you have additional insight into the issue, or still need help with the sample, please reopen. Thanks.
