### ISSUE TITLE
redirect_uri issue

### ISSUE THREAD

**Issue by legendvijay** [OfficeDev/O365-ASPNETMVC-Start#19]
redirect_uri in address bar while login Considers localIp instead Public , what i mentioned in Azure Account in the configuration
If i manually change the redirect url to public then it works.

**Comment by MIchaelMainer** [comment]
Help me understand. Is there an error in the ReadMe? Can you provide me the steps you used?

**Comment by legendvijay** [comment]
Not an error,
by changing the base_url in startup.auth.cs resolved my problem .
Thank you for for your response.
