### ISSUE TITLE
Package.config Issue

### ISSUE THREAD

**Issue by ashuetawah** [OfficeDev/O365-ASPNETMVC-Start#20]
The new [package.config](https://raw.githubusercontent.com/OfficeDev/O365-ASPNETMVC-Start/master/O365-APIs-Start-ASPNET-MVC/packages.config) has double entries for the ```GraphClient``` and ```Newtonsoft.json``` at [line 14](https://github.com/OfficeDev/O365-ASPNETMVC-Start/blob/master/O365-APIs-Start-ASPNET-MVC/packages.config#L14) and [44](https://github.com/OfficeDev/O365-ASPNETMVC-Start/blob/master/O365-APIs-Start-ASPNET-MVC/packages.config#L44).

**Comment by MIchaelMainer** [comment]
Closed with @iambmelt change.
