### ISSUE TITLE
Problem publishing in Azure Web site with Azure DB

### ISSUE THREAD

**Issue by jomague46** [OfficeDev/O365-ASPNETMVC-Start#26]
I am facing strange issue, I'm following this sample. I follow all steps and Works succesfully in localhost but when I deploy the same app on Microsoft Azure, it throws the following exception Failed to acquire token silently. Call method AcquireToken. My code runs perfectly against localhost but not on azure. In both cases the App connects to database without problems but there is problems with ADALTokenCache in a Azure Web Site.

I would need steps to publish this sample or similar in a Azure Website and Azure DB. Is possible?

Others samples like O365-WebApp-SingleTenant or O365-WebApp-MultiTenant have the same problem. 

<img width="763" alt="error" src="https://cloud.githubusercontent.com/assets/11057364/10306620/9496efdc-6c28-11e5-8e85-15e578f58d76.PNG">

**Comment by MIchaelMainer** [comment]
Can you share with us the steps you took to host this on Azure?

**Comment by MIchaelMainer** [comment]
Closing due to no reply.
