### ISSUE TITLE
Not able to upload more than 50 MB to OneDrive office 365 

### ISSUE THREAD

**Issue by JeevaJose** [OfficeDev/O365-ASPNETMVC-Start#27]
I am using “O365-APIs-Start-ASPNET-MVC” application to upload the file to office365 account. This was working perfectly on last week but yesterday onwards I was not able to upload more than 50 MB as single file.

If I try with more than 50 MB the file is not get uploading. During the upload I could not see any errors.

Please let me know this is API issue or Office 365 issue.

https://msdn.microsoft.com/en-us/office/office365/api/files-rest-operations

**Comment by MIchaelMainer** [comment]
@JeevaJose can you provide a Fiddler trace of the failed request?

**Comment by JeevaJose** [comment]
I used fiddler debugger to track the issue and found that I was getting following message.

{"error":{"code":"-1, Microsoft.SharePoint.Client.InvalidClientQueryException","message":"
The request message is too big. The server does not allow messages larger than 52428800 bytes."}}

Looks Microsoft rest API having issue.

**Comment by MIchaelMainer** [comment]
Can you provide the request+response, body+headers as well so that we can use the diagnostics information? Make sure you clear out any personal info.

**Comment by JeevaJose** [comment]
Thanks for your support.
Could you please try to upload 100 MB file to OneDrive. I just want to check whether larger files are able to upload from your end. 
I will also provide the fiddler response.

**Comment by JeevaJose** [comment]
Looks this is an inconsistent issue in Office 365 apis.

**Comment by MIchaelMainer** [comment]
Closing this since I haven't received the requested diagnostics information. One thing I do suggest is that for OneDrive, there is a much better [client API](https://github.com/onedrive/onedrive-sdk-csharp).
