### ISSUE TITLE
Failed to acquire token silently. Call method AcquireToken

### ISSUE THREAD

**Issue by mosoccer** [OfficeDev/O365-ASPNETMVC-Start#28]
Downloaded zip of project and followed the readme directions.  When I run the app, I'm able to log into it via Azure AD just fine and see my email address at the top, but as soon as I click on any of the buttons in the page (Calendar, Email, etc) I get an error:

Failed to acquire token silently. Call method AcquireToken

Including StackTrace:

Microsoft.IdentityModel.Clients.ActiveDirectory.AdalSilentTokenAcquisitionException: Failed to acquire token silently. Call method AcquireToken at O365_APIs_Start_ASPNET_MVC.Controllers.CalendarController.<Index>d__4.MoveNext() in C:\Users\xxxxxx\Downloads\O365-ASPNETMVC-Start-master\O365-APIs-Start-ASPNET-MVC\Controllers\CalendarController.cs:line 69 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d() at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f() at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End() at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult) at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by MIchaelMainer** [comment]
Can you confirm that all of the permissions were set for the application?

**Comment by mosoccer** [comment]
Yes I have confirmed the permissions have been set, see attached.
![capture](https://cloud.githubusercontent.com/assets/581426/11372163/954c0e46-9291-11e5-86a8-bcceb319dc79.PNG)

**Comment by MIchaelMainer** [comment]
Did you get the consent screen when you logged in? Did the signed-in user have access to those resources? I notice that when I'm signed into manage.windowsazure.com with my @Hotmail address, I'm getting the consent screen using my @Hotmail account instead of my O365 account. 

![consent](https://cloud.githubusercontent.com/assets/8527305/11480013/fd446270-9749-11e5-9565-73e2e6257edd.png)

This sample is single tenant. Did you leave the default value of single-tenant? 

I just ran through the instructions again and it worked as expected.

**Comment by mosoccer** [comment]
I did not get a consent screen when I logged in and I made sure to sign in with my O365 account email.  I'm not sure if a permission on our O365 is missing but when I go the Sandbox API site:  https://apisandbox.msdn.microsoft.com/

And try to login I was originally getting an error that said "Does not have access to consent".  We tried to make some O365 permission changes and now I get an error that says:  "Calling principal cannot consent due to lack of permissions."   Are we missing a permission or setting somewhere that could be causing this as well as an issue when trying to run this code example?

**Comment by MIchaelMainer** [comment]
I was able to reproduce the issue when I ran Fiddler when I tried to access the files, mail, or calendar resources. The sample had an issue with Fiddler being a MITM, and I got the error. Then I turn Fiddler off.  Then the sample is in a state where it needs to acquire the token (again). If I go to http://localhost:27592/Account/RefreshSession, it get backs to the expected state.

Does navigating to http://localhost:27592/Account/RefreshSession resolve make the sample work for you? Make sure Fiddler is off.

Nonetheless, there is an issue in this sample in the authentication part of it.

**Comment by mosoccer** [comment]
I do not yet have Fiddler installed on this test machine.

When I go to /Account/RefreshSession I see it quickly jump to login.microsoft..... and then back to the app, but when I again click on any of the buttons for files, mail, calendar I get the same AdalException error.

**Comment by MIchaelMainer** [comment]
Strange. There is something going on here that I don't understand and I can't reproduce. Do you experience the same issue if you use this sample: https://github.com/OfficeDev/O365-WebApp-MultiTenant

**Comment by MIchaelMainer** [comment]
@mosoccer Can you try going into packages.config and change Microsoft.Owin to version 3.0.1? Rebuild and run the project. Make sure the nuget package updates. 

Does that make a difference?

**Comment by mosoccer** [comment]
Same exception with Owin 3.0.1.

Also same error with the MultiTenant Example:
    Message: "Failed to acquire token silently. Call method AcquireToken"
    Source: "Microsoft.IdentityModel.Clients.ActiveDirectory"

**Comment by mosoccer** [comment]
I pulled up the project again today to play with and dig into and magically it's working now.  I haven't changed anything in the project since the last time I tried it and we haven't changed any settings on our O365 side.  Aware of anything changing service side?

**Comment by mosoccer** [comment]
I spoke too soon, Contacts still gives same error as before but Calendar, Email and Files all work as expected.

**Comment by MIchaelMainer** [comment]
I'm unaware of any changes/fixes in the service that may have made it work. I do find it odd that the Contacts doesn't work but the Calendar and Email APIs do work. I can only suggest checking that the token has the Contacts.Write scope (or checking the registration on Azure).

**Comment by MIchaelMainer** [comment]
I was unable to repro the issue. Please reopen this issue if you can provide new information about the problem.

**Comment by redoinerraiss** [comment]
i have a similar problem about **ADAL EXCEPTION**

 however i selected in "connected services" all permissions 
![image](https://cloud.githubusercontent.com/assets/17815609/13730993/92a44418-e95f-11e5-973c-06e936484dd1.png)
![image](https://cloud.githubusercontent.com/assets/17815609/13730927/d1c7dad0-e95d-11e5-844f-59d64c23547c.png)
i can log in inside my application no problem but when i want to access to my Calendar ,Contacts,Email and My Files i have adal exception
I have this error :
_AdalException_
_This exception is thrown when either you have a stale O365 access token that can cause authentication errors, or you attempted to access a resource that you don't have permissions to access._
![image](https://cloud.githubusercontent.com/assets/17815609/13730960/a2efe260-e95e-11e5-8b18-f9f8b3fb23ef.png)
My application is active in my Office 365 account:
![image](https://cloud.githubusercontent.com/assets/17815609/13731024/20b4e474-e960-11e5-899b-685473adb617.png)

Someone can help me i don't know if  i must configure anything in my Office 365 Admin or If i must associate my account Office 365 to my Azure AD ?

**Comment by jamescro** [comment]
Have you followed the instructions for [associating your Azure subscription with your Office 365 account](https://msdn.microsoft.com/en-us/office/office365/howto/setup-development-environment)?

**Comment by adiazcan** [comment]
I've got the same issue but Only when I try with a AD FS Tenant. 

The same code works on a non-federate tenant but it's failed when a try with a Federate Tenant. 

Any help?
