### ISSUE TITLE
Will this work with Exchange 2016 on-premise?

### ISSUE THREAD

**Issue by rdev5** [OfficeDev/O365-ASPNETMVC-Start#29]
Just posting this here as it stated: "You can send your questions and suggestions to us in the Issues section"

Two questions:
- Will this project work against Exchange 2016 on-premise?
- Can this be used to create a **very specific** SSO experience whereby: 1) an auth cookie/token is retrieved on behalf of and in turn relayed back to the user and 2) the user is able to open their Inbox in Outlook on the web?

If so, what API endpoints (sample code would even be preferred) do we have to work with?

Thanks!

**Comment by MIchaelMainer** [comment]
Hello @rdev5 

* I don't think that the REST APIs have been exposed via Exchange 2016 on-premise. I don't have an Exchange 2016 topology to test this against.
* I haven't read anything about the SSO story along with the Office 365 APIs story. I haven't worked on a sample that does this. I'm interested to know what that story is as well. I suggest you start with [active-directory-dotnet-web-single-sign-out ](https://github.com/Azure-Samples/active-directory-dotnet-web-single-sign-out). I know that is the sign out scenario, but perhaps you can ask the creator of that sample to point at a SSOn sample. I'm not finding much on this (search for ADAL + SSO)

I'm sorry I couldn't be more helpful. I'm going to keep this issue in mind. 
With regards.
