### ISSUE TITLE
Empty content when login 

### ISSUE THREAD

**Issue by chenjinhui314** [OfficeDev/O365-ASPNETMVC-Start#31]
Hi guys,

I am using this sample for test,first time, it works, 
But, I got a empty page in second(third...) time, in the console, I can see the response message "Failed to load content" on the network tab(I am using chrome).
Why the code can work once, but always failed next time?

Thanks all you help :)

**Comment by MIchaelMainer** [comment]
Can you show some screen shots of what is happening?

**Comment by chenjinhui314** [comment]
I just get a white page, it works today :(

**Comment by jamescro** [comment]
If this is working for you now the issue appears to have been transient. Please re-open if the problem recurs.
