### ISSUE TITLE
Not able to add attachment to calendar event

### ISSUE THREAD

**Issue by jsutharjsuthar4** [OfficeDev/O365-ASPNETMVC-Start#33]
Hi. I am trying to add attachment to calendar. As it requires event id I can't add using method AddCalendarEventAsync. So I'm trying to update event using below code:

`var outlookServicesClient = await AuthenticationHelper.EnsureOutlookServicesClientCreatedAsync("Calendar");`
`var thisEventFetcher = outlookServicesClient.Me.Calendar.Events.GetById(selectedEventId);`
`IEvent eventToUpdate = await thisEventFetcher.ExecuteAsync();`

But 'eventToUpdate' has not Attachment set property. Please could you check this and explain how to add attachment to calendar.

Thank you.

**Comment by jamescro** [comment]
There should be an Attachments collection on that event, and you should be able to add an attachment to that collection. Do you not see the collection?

**Comment by jsutharjsuthar4** [comment]
Ok I am using api version v1.0. In "AddCalendarEventAsync" method adding attachment after setting event's basic info and saving event as below. The event is added to the calendar but without any attachment. I checked in fiddler, no attachment data is passing in the request.
```
....
 Event newEvent = new Event
            {
                Subject = Subject,
                Location = location,
                Attendees = attendees,
                Start = start,
                End = end,
                Body = body
            };
			
Attachment attachment = new Microsoft.Office365.OutlookServices.FileAttachment
                        {
                            Name = "test",
                            ContentBytes = File.ReadAllBytes(@"D:\test.jpeg"),
                            ContentType = "image/jpeg"
                        };		
 newEvent.Attachments.Add(attachment);	
 try
            {
                // Make sure we have a reference to the Outlook Services client
                var outlookServicesClient = await AuthenticationHelper.EnsureOutlookServicesClientCreatedAsync("Calendar");

                // This results in a call to the service.
                await outlookServicesClient.Me.Events.AddEventAsync(newEvent);
                await ((IEventFetcher)newEvent).ExecuteAsync();
                newEventId = newEvent.Id;
            }
...
```
As per documentation [(https://msdn.microsoft.com/en-us/office/office365/api/calendar-rest-operations#Createattachments)] it requires eventid to save attachment.
 So I was using code in 'UpdateCalendarEventAsync' method. Just like how attachment works with emails, you save as draft and add attachment to that draft.  But I am not sure how to add attachments there. As Attachments has no set property for "IEvent" interface. 

Please could you check this issue.
Many Thanks,

**Comment by jsutharjsuthar4** [comment]
Hi. I have figured out how to add attachment to the calendar event. Thanks.

**Comment by hemanth1707113** [comment]
Hi,

Can you please provide sample code , How to add attachement to the calender event.

I am also stuck with same place like  The event is added to the calendar with  attachment but in recipients  got the event mail with out attachment .


Thanks,
Hemanth.
