### ISSUE TITLE
Deleting calendar attachment

### ISSUE THREAD

**Issue by jsutharjsuthar4** [OfficeDev/O365-ASPNETMVC-Start#34]
Hi,
I was trying to delete calendar attachment using following code which results in error "The segment type 'TypeSegment' requested as 'Microsoft.OutlookServices.FileAttachment' is not implemented."

`var outlookServicesClient = await AuthenticationHelper.EnsureOutlookServicesClientCreatedAsync("Calendar");
 var thisEventFetcher = outlookServicesClient.Me.Calendar.Events.GetById(eventID);
                            var thisEventAttachments = await thisEventFetcher.Attachments.ExecuteAsync();
                            for (int j = 0; j < thisEventAttachments.CurrentPage.Count; j++)
                            {
                                if (attachmentID == thisEventAttachments.CurrentPage[j].Id)
                                {
                                    await thisEventAttachments.CurrentPage[j].DeleteAsync();   
                                }
                            } `

I did check DeleteAsync in fiddler  which passes 'Microsoft.OutlookServices.FileAttachment' at the end of the request and while intercepting if I remove it then I successfully deletes attachments from the calendar event.

Please could you check why its passing 'Microsoft.OutlookServices.FileAttachment' at the end of 
`DELETE https://outlook.office365.com/api/v1.0/Users('emailid')/Events('eventID')/Attachments('attachmentID')/Microsoft.OutlookServices.FileAttachment HTTP
`

Thanks,

**Comment by jamescro** [comment]
This looks like bug in the library (and not in the sample). I will pass this along to the relevant people to see if we can learn more.

**Comment by jsutharjsuthar4** [comment]
Hi @jamescro  Is there any update regarding this issue?

**Comment by jamescro** [comment]
I've pinged the engineering team again.

**Comment by jamescro** [comment]
Could you try upgrading the solution to use the v2.0 version of the [OutlookServices client library](http://www.nuget.org/packages/Microsoft.Office365.OutlookServices-V2.0/) and see if you can duplicate the problem with that version?

**Comment by jsutharjsuthar4** [comment]
Thank @jamescro  for replying. If you could provide sample code for v2.0 version of the OutlookServices client library would be great. As I got errors on building the project and found this new library is using different datatypes and renamed column names.

Thanks,

**Comment by jsutharjsuthar4** [comment]
Hello @jamescro  I managed to resolve errors with new V2.0 version of outllookservices client library and I got same error "TypeSegment' requested as 'Microsoft.OutlookServices.FileAttachment' is not implemented" .

**Comment by jamescro** [comment]
Thanks for doing that work. It appears that this is broken in both versions of the OutlookServices SDK, so for now the only alternative is to use the raw REST call that works. I will follow up about what we can do to fix this in the SDKs.

**Comment by jsutharjsuthar4** [comment]
Hi @jamescro ,
Has this issue been solved? Have SDK been fixed?

Thanks,

**Comment by jamescro** [comment]
Unfortunately, no. I haven't gotten any word on when this could be fixed in the SDK. At this point, using the REST call is your best option.
