### ISSUE TITLE
error/Nothing happened when call AcquireTokenSilentAsync method[Office365]

### ISSUE THREAD

**Issue by MJems** [OfficeDev/O365-ASPNETMVC-Start#35]
I converted this into ASP.NET, and when it called below code(AcquireTokenSilentAsync) nothing happened. can anyone please help me to fix this issue ASAP.
 

`internal static async Task<OutlookServicesClient> EnsureOutlookServicesClientCreatedAsync(string capabilityName)
    {
        var signInUserId = ClaimsPrincipal.Current.FindFirst(ClaimTypes.NameIdentifier).Value;
        var userObjectId = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/objectidentifier").Value;
        var tenantId = ClaimsPrincipal.Current.FindFirst("http://schemas.microsoft.com/identity/claims/tenantid").Value;

        AuthenticationContext authContext = new AuthenticationContext(string.Format("{0}/{1}", SettingsHelper.AuthorizationUri, tenantId), new ADALTokenCache(signInUserId));
         
        try
        {
            DiscoveryClient discClient = new DiscoveryClient(SettingsHelper.DiscoveryServiceEndpointUri,
                async () =>
                {
                    var authResult = await authContext.AcquireTokenSilentAsync(SettingsHelper.DiscoveryServiceResourceId, new ClientCredential(SettingsHelper.ClientId, SettingsHelper.AppKey), new UserIdentifier(userObjectId, UserIdentifierType.UniqueId));

                    return authResult.AccessToken;
                });

            var dcr = await discClient.DiscoverCapabilityAsync("Contacts");

            return new OutlookServicesClient(dcr.ServiceEndpointUri,
                async () =>
                {
                    var authResult = await authContext.AcquireTokenSilentAsync(dcr.ServiceResourceId, new ClientCredential(SettingsHelper.ClientId, SettingsHelper.AppKey), new UserIdentifier(userObjectId, UserIdentifierType.UniqueId));

                    return authResult.AccessToken;
                });
        }
        catch (AdalException exception)
        {
            //Handle token acquisition failure
            if (exception.ErrorCode == AdalError.FailedToAcquireTokenSilently)
            {
                authContext.TokenCache.Clear();
                throw exception;
            }
            return null;
        }
        catch (Exception ex)
        {
            
            throw;
        }
    }`

**Comment by jamescro** [comment]
Your sample attachment doesn't contain a .csproj or solution file, so I can't run it. Is the call throwing an exception? If so, could you provide the details (including the inner exception)? Could you also run your code with the debugger and check the values that are being passed to the AcquireTokenSilentAsync method? If the call is going out and generating an exception, could you provide a Fiddler trace as well?

**Comment by MJems** [comment]
I did, it shows me object reference error. this is website so no need for .csproj.

can you open as website and check, I tried with all ways but no success.

**Comment by MJems** [comment]
I fixed it. and working now.
