### ISSUE TITLE
How can i get Tenant ID ?

### ISSUE THREAD

**Issue by bhallaheemanshu** [OfficeDev/O365-ASPNETMVC-Start#41]
Do i need to put my credit card info in AZURE AD to get my tenant id ? 

I am getting below error after running the solution file - 

**Oops you've reached an error!

Looks like you may not have entered the value of your tenant ID in the web.config file in your project. Follow the instructions in the readme to get this value from the Azure portal and copy it into the web.config file. The readme file is in the solution (README.MD), and you can also view it online at Office 365 Starter Project Readme.**

**Comment by bhallaheemanshu** [comment]
**3. A Services Manager window will appear. Choose Office 365 -> Office 365 APIs and select the Register your app link.**

I have seen above point in github documentation but i am unable to found register your app link after selecting office 365 APIs as discussed in step . 

Attached pic is screenshot for that . It is asking me for domain but i don't know what to fill in it. I am having office 365 login As 'test@deftsoft.onmicrosoft.com'

**Comment by DianeD** [comment]
Hi bhallaheemanshu. Please enter this:  deftsoft.onmicrosoft.com

**Comment by bhallaheemanshu** [comment]
ok @DianeD  Thanks let me try

**Comment by bhallaheemanshu** [comment]
@DianeD  thanks that thing worked but i am getting anerror . I think that's due i am not having subscription in azure that needs to add credit card info . and we must require to fill credit card info to get azure subscription

Error i am getting : User account '' from identity provider 'live.com' does not exist in tenant '' and cannot access the application '' in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

**Is that due to I am not having subscription of azure**

**Comment by DianeD** [comment]
Yes, it sounds like you need to follow the steps here:
https://msdn.microsoft.com/en-us/office/office365/howto/setup-development-environment#bk_AssociateNewAzureSubscription

But can you look at this sample to see if it suits your needs? It makes similar calls to the Microsoft Graph but uses the v2 auth endpoint, so it is easier to register and also supports Microsoft accounts.
https://github.com/microsoftgraph/aspnet-connect-sample

**Comment by bhallaheemanshu** [comment]
@DianeD  Thanks for the useful info you provided . 

I am having office 365 account but how its different from Office 365 Business Account . I am not sure whether i am having office 365 Business account or not . I have also not paid anything to azure and not integrated credit card

I got below error in Step for Associating Office 365 with Azure

![azure](https://cloud.githubusercontent.com/assets/7411405/17955959/9b877242-6aa3-11e6-9b2c-bcd879c2ab5c.PNG)

**Comment by bhallaheemanshu** [comment]
This is the Step / Point I got Stuck 
 Step for Associating Office 365 with Azure

I got error given in pic in above comment
