### ISSUE TITLE
ParentReference.Id always returns the ID of the Root Onedrive Folder.

### ISSUE THREAD

**Issue by celloudiallo** [OfficeDev/O365-ASPNETMVC-Start#9]
anyFolder = await ctx.Files[folderId].ToFolder().ExecuteAsync();
anyFolder.ParentReference.Id always return the ID of the Root OneDrive Folder.
Is this by design or is it supposed to return the ID of its direct parent?

**Comment by MIchaelMainer** [comment]
celloudiallo,
I'm looking into this. I see the same behavior that you observe. I will respond here when I get more information. The only way that I see right now to work around this is to use the sharePointClient.Files.GetByPathAsync("pathToParentFolder") to get the parent folder, and its identifier. I know, that is an extra call. I will respond once I have some info on ParentReference.ID.

**Comment by kotsak** [comment]
I've experienced the same even when using the Files REST API directly.

**Comment by MIchaelMainer** [comment]
Sorry for the late reply folks. I've made the product team aware of the issue -- I opened a bug on this. I'll report back here when I get more information.

**Comment by MIchaelMainer** [comment]
This appears to have been fixed. Please reopen if you observe otherwise.
